baseURL = 'https://yildirimmuhendislikdanismanlik.com/'
languageCode = 'en-us'
title = 'Yıldırım Mühendislik Danışmanlık Hizmetleri'
theme = "paper"
canonifyURLs=true
[pagination]
  pagerSize = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  

rss = true

[params]
  color = 'linen'
  instagram = 'yildirimmuhendislikduzce'           # instagram.com/YOUR_INSTAGRAM_ID
  logo = "/logo.svg"
  disablePathToLower = true
  relativeURLs = true
  uglyURLs = false
  bio="Mühendislik Bürosu"

[params.navigation]
    #other stuff
    

avatar = '/images/nihat-sami-yildirim.jpg'
  name = 'Nihat Sami Yıldırım'
  bio = 'Jeofizik Mühendisi'

[menu]
  [[menu.main]]
    identifier = "services"
    name = "Hizmetler"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Hakkımızda"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "resources"
    name = "Kaynaklar"
    url = "/resources/"
    weight = 3

  [[menu.main]]
    identifier = "yemin"
    name = "Mühendislik Yemini"
    url = "/muhendislik-yemini/"
    weight = 4


#[params.giscus]
#  repo = "ashwor11/yildirimmuhendislik-comments"
#  repoId=  "R_kgDOOBccuA"
#  category = "Announcements"
#  categoryId = "DIC_kwDOOBccuM4CndJ8"
#  mapping = "pathname"
#  theme = "light"
#  lang = "tr"

  
